### ISSUE TITLE
add ISO 8601 Duration regex to schema

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#244]
WCMP2 defines `time.resolution` as an ISO 8601 Duration string.  Our [JSON Schema defines `time.resolution`](https://github.com/wmo-im/wcmp2/blob/main/schemas/wcmpRecordGeoJSON.yaml#L54-L59) as follows:

```yaml
          resolution:
            type: string
            description:
              Minimum time period resolvable in the dataset, as an ISO 8601 duration
            example:
              - 'P1D'
```

A regular expression can further validate ISO 8601 Duration syntax.  Proposed regex (from https://rgxdb.com/r/MD2234J):

`/^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/`

```yaml
          resolution:
            type: string
            description:
              Minimum time period resolvable in the dataset, as an ISO 8601 duration
            pattern: '^(-?)P(?=\\d|T\\d)(?:(\\d+)Y)?(?:(\\d+)M)?(?:(\\d+)([DW]))?(?:T(?:(\\d+)H)?(?:(\\d+)M)?(?:(\\d+(?:\\.\\d+)?)S)?)?$'
            example:
              - 'P1D'
```

(Note: the double escapes and removal of regex anchors are for JSON Schema compliance).
